---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:1.7.4   # Adjust as needed or use latest
    container_name: obsidian    # Adjust as needed
    security_opt:
      - seccomp:unconfined  # Optional Docker security parameter. ! Comment out or delete for better security !
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC  # Adjust timezone as needed
    volumes:
      - /path/to/config:/config # Optional, adjust if needed, comment out if not used
      - /path/on/host/for/use/within:/host_docs # Optional, adjust if needed, comment out if not used (for documents, etc.)
    ports:
      - 3000:3000   # http port for Firefox access, comment out if not needed
      - 3001:3001   # https port for Firefox access, adjust if needed
    devices:
      - /dev/dri:/dev/dri   # Optional, used for Direct Rendering Infrastructure on host (DRI)
    shm_size: "1gb"
    restart: unless-stopped
