services:

  registry:
    container_name: registry
    image: registry:2.8.3 # Update with custom or latest Docker image
    restart: unless-stopped
    networks:
      - registry-network
    ports:
      - 5000:5000/tcp # Replace Registry port as needed
    extra_hosts:
      - FQDN:xxx.xxx.xxx.xxx  # Added for hostname resolving (optional)
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /path/to/certificate/certificate.crt # Replace with your path and certificate file name
      REGISTRY_HTTP_TLS_KEY: /path/to/private/key/private.key # Replace with your path and private key file name
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd # Replace with your path and htpasswd file name
      REGISTRY_AUTH_HTPASSWD_REALM: 'Registry Realm'
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://FQDN:8080]' # Replace FQDN and PORT as needed
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD, GET, OPTIONS, DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization, Accept, Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
    volumes:
      - /path/to/docker-registry/certs:/certs # Adjust path or replace bind mount with dedicated volume if needed
      - /path/to/docker-registry/auth:/auth # Adjust path or replace bind mount with dedicated volume if needed
      - /path/to/docker-registry/data:/var/lib/registry # Adjust path or replace bind mount with dedicated volume if needed

  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:2.5.7 # Update with custom or latest Docker image
    restart: unless-stopped
    depends_on:
      - registry
    networks:
      - registry-network
    ports:
      - 8080:80/tcp # Replace Registry UI port as needed
    extra_hosts:
      - FQDN:xxx.xxx.xxx.xxx  # Added for hostname resolving (optional)
    environment:
      SINGLE_REGISTRY: false
      REGISTRY_TITLE: 'Private Docker Registry UI'
      DELETE_IMAGES: true
      SHOW_CONTENT_DIGEST: true
      NGINX_PROXY_PASS_URL: 'https://FQDN:5000'
      SHOW_CATALOG_NB_TAGS: true
      CATALOG_MIN_BRANCHES: 1
      CATALOG_MAX_BRANCHES: 1
      TAGLIST_PAGE_SIZE: 100
      REGISTRY_SECURED: true
      CATALOG_ELEMENTS_LIMIT: 1000

networks:
  registry-network:
    name: registry-network
